// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZLkBAXRNxHj5IE5jU0v83y9jLenf3Lig',
    appId: '1:886658242291:web:17c9ca4a57eec47e134986',
    messagingSenderId: '886658242291',
    projectId: 'authapp-3cc9d',
    authDomain: 'authapp-3cc9d.firebaseapp.com',
    storageBucket: 'authapp-3cc9d.appspot.com',
    measurementId: 'G-6MQT0EXTVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvjnKu-NQJXYrRySZPVqxOPPLvIdZGuhY',
    appId: '1:886658242291:android:ffe66c0ebabe8342134986',
    messagingSenderId: '886658242291',
    projectId: 'authapp-3cc9d',
    storageBucket: 'authapp-3cc9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOMwLQnnrtz4YUqdXSH_4Lzep46aZ2TH4',
    appId: '1:886658242291:ios:a50510181b303f05134986',
    messagingSenderId: '886658242291',
    projectId: 'authapp-3cc9d',
    storageBucket: 'authapp-3cc9d.appspot.com',
    iosBundleId: 'com.example.te',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOMwLQnnrtz4YUqdXSH_4Lzep46aZ2TH4',
    appId: '1:886658242291:ios:a50510181b303f05134986',
    messagingSenderId: '886658242291',
    projectId: 'authapp-3cc9d',
    storageBucket: 'authapp-3cc9d.appspot.com',
    iosBundleId: 'com.example.te',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZLkBAXRNxHj5IE5jU0v83y9jLenf3Lig',
    appId: '1:886658242291:web:fc1c861e7e6a4f59134986',
    messagingSenderId: '886658242291',
    projectId: 'authapp-3cc9d',
    authDomain: 'authapp-3cc9d.firebaseapp.com',
    storageBucket: 'authapp-3cc9d.appspot.com',
    measurementId: 'G-S8RF9H1BD5',
  );

}